using MarketPlace.Application.Services.EntityServices.Account;
using MarketPlace.Application.Services.EntityServices.Common;
using MarketPlace.Application.Services.EntityServices.Contents;
using MarketPlace.Application.Services.EntityServices.MultiMediaFiles;
using MarketPlace.Application.Services.EntityServices.Products;
using MarketPlace.Application.Services.EntityServices.StoretSettings;
using MarketPlace.Application.Services.EntityServices.Tags;
using MarketPlace.Application.Validations;
using MarketPlace.Domain.Repositories.Common;
using MarketPlace.Dto.Comments;
using MarketPlace.Dto.Posts;
using MarketPlace.Infrastructure.Repositories.Common;
using MarketPlace.Infrastructure.Services.EntityServices.Account;
using MarketPlace.Infrastructure.Services.EntityServices.Account.Identity;
using MarketPlace.Infrastructure.Services.EntityServices.Comments;
using MarketPlace.Infrastructure.Services.EntityServices.Common;
using MarketPlace.Infrastructure.Services.EntityServices.Contents;
using MarketPlace.Infrastructure.Services.EntityServices.MultiMediaFiles;
using MarketPlace.Infrastructure.Services.EntityServices.Orders;
using MarketPlace.Infrastructure.Services.EntityServices.Orders.Invoices;
using MarketPlace.Infrastructure.Services.EntityServices.Posts;
using MarketPlace.Infrastructure.Services.EntityServices.Products;
using MarketPlace.Infrastructure.Services.EntityServices.Products.Installment;
using MarketPlace.Infrastructure.Services.EntityServices.Products.Pricing;
using MarketPlace.Infrastructure.Services.EntityServices.Products.ProductTypes;
using MarketPlace.Infrastructure.Services.EntityServices.PspLog;
using MarketPlace.Infrastructure.Services.EntityServices.SiteSettings;
using MarketPlace.Infrastructure.Services.EntityServices.StoretSettings;
using MarketPlace.Infrastructure.Services.EntityServices.StoretSettings.Selling.PayGateSetting;
using MarketPlace.Infrastructure.Services.EntityServices.StoretSettings.Selling.Promotions;
using MarketPlace.Infrastructure.Services.EntityServices.StoretSettings.Selling.Setting;
using MarketPlace.Infrastructure.Services.EntityServices.StoretSettings.Selling.Shippings;
using MarketPlace.Infrastructure.Services.EntityServices.StoretSettings.Settings;
using MarketPlace.Infrastructure.Services.EntityServices.StoretSettings.Users;
using MarketPlace.Infrastructure.Services.EntityServices.Tags;
using MarketPlace.Infrastructure.Services.JWT;
using Microsoft.Extensions.DependencyInjection;
using MarketPlace.Dto.Products;
using FluentValidation;
using MarketPlace.Dto.Orders.Invoices;
using MarketPlace.Dto.Orders;
using MarketPlace.Dto.Products.Installment;
using MarketPlace.Dto.Products.Pricing;
using MarketPlace.Dto.PspLog;
using MarketPlace.Dto.SiteSettings;
using MarketPlace.Dto.StoretSettings.Selling.PayGateSetting;
using MarketPlace.Dto.StoretSettings.Selling.Promotions;
using MarketPlace.Dto.StoretSettings.Selling.Setting;
using MarketPlace.Dto.StoretSettings.Settings;
using MarketPlace.Dto.StoretSettings.Shippings;
using MarketPlace.Dto.StoretSettings.Slider;
using MarketPlace.Dto.StoretSettings.Users;
using MarketPlace.Dto.StoretSettings;
using MarketPlace.Dto.Tags;
using MarketPlace.StoretSettings.Settings;
using MarketPlace.Infrastructure.Services.EntityServices.Categories;
using MarketPlace.Application.Services.EntityServices.Categories;
using MarketPlace.Application.Services.EntityServices.Comments;
using MarketPlace.Dto.Media;
using MarketPlace.Dto.Admin;
using MarketPlace.Application.Services.EntityServices.Admin;
using MarketPlace.Infrastructure.Services.EntityServices.Admin;
using MarketPlace.Application.Services.EntityServices.Orders.Invoices;
using MarketPlace.Application.Services.EntityServices.Orders;
using MarketPlace.Application.Services.EntityServices.Posts;
using MarketPlace.Application.Services.EntityServices.PspLog;
using MarketPlace.Application.Services.EntityServices.SiteSettings;
using MarketPlace.Application.Services.EntityServices.StoretSettings.PayGateSetting;
using MarketPlace.Application.Services.EntityServices.StoretSettings.Setting;
using MarketPlace.Application.Services.EntityServices.StoretSettings.Settings;
using MarketPlace.Dto.Contents;
using MarketPlace.Dto.Products.ProductTypes;

namespace MarketPlace.Infrastructure.Extensions;

public static class IServiceCollectionExtensions
{
    public static void AddMarketPlaceServices(this IServiceCollection services)
    {
        services.AddScoped(typeof(IBaseRepository<>), typeof(BaseRepository<>));
        services.AddScoped(typeof(IBaseService<,,>), typeof(BaseService<,,>));

        services.AddScoped(typeof(CustomeUserManager));
        services.AddScoped<OtpTokenProvider>();
        services.AddScoped<IJwtService, JwtService>();

        services.AddScoped<IValidator<ProductRequestDto>, ProductValidation>();
        services.AddScoped<IValidator<BrandRequestDto>, BrandValidation>();
        services.AddScoped<IValidator<CommentRequestDto>, CommentValidation>();
        services.AddScoped<IValidator<ProductContentRequestDto>, ContentValidation>();
        services.AddScoped<IValidator<CouponRequestDto>, CouponValidation>();
        services.AddScoped<IValidator<CreateProductRequestDto>, CreateProductValidation>();
        services.AddScoped<IValidator<DiscountPriceRequestDto>, DiscountPriceValidation>();
        services.AddScoped<IValidator<FAQRequestDto>, FAQValidation>();
        services.AddScoped<IValidator<InvoiceRequestDto>, InvoiceValidation>();
        services.AddScoped<IValidator<MenuRequestDto>, MenuValidation>();
        services.AddScoped<IValidator<OrderNoteRequestDto>, OrderNoteValidation>();
        services.AddScoped<IValidator<OrderTrackingRequestDto>, OrderTrackingValidation>();
        services.AddScoped<IValidator<PayPalSettingRequestDto>, PayPalSettingValidation>();
        services.AddScoped<IValidator<PostRequestDto>, PostValidation>();
        services.AddScoped<IValidator<PriceRequestDto>, PriceValidation>();
        services.AddScoped<IValidator<DownloadableFileRequestDto>, DownloadableFileValidation>();
        services.AddScoped<IValidator<ProductInstallmentRequestDto>, ProductInstallmentValidation>();
        services.AddScoped<IValidator<ProductSpecialOfferRequestDto>, ProductSpecialOfferValidation>();
        services.AddScoped<IValidator<PspSadadLogRequestDto>, PspSadadLogValidation>();
        services.AddScoped<IValidator<ShippingClassRequestDto>, ShippingClassValidation>();
        services.AddScoped<IValidator<ShippingMethodRequestDto>, ShippingMethodValidation>();
        services.AddScoped<IValidator<ShippingOptionRequestDto>, ShippingOptionValidation>();
        services.AddScoped<IValidator<ShippingZoneRequestDto>, ShippingZoneValidation>();
        services.AddScoped<IValidator<StoreAddressRequestDto>, StoreAddressValidation>();
        services.AddScoped<IValidator<StoreDiscussionSettingRequestDto>, StoreDiscussionSettingValidation>();
        services.AddScoped<IValidator<StoreGeneralSellingSettingsRequestDto>, StoreGeneralSellingSettingsValidation>();
        services.AddScoped<IValidator<StoreGeneralSettingRequestDto>, StoreGeneralSettingValidation>();
        services.AddScoped<IValidator<StoreGroupRequestDto>, StoreGroupValidation>();
        services.AddScoped<IValidator<StoreInventorySettingRequestDto>, StoreInventorySettingValidation>();
        services.AddScoped<IValidator<StoreLowThresoldNotificationManagmentSettingRequestDto>,
            StoreLowThresoldNotificationManagmentSettingValidation>();
        services.AddScoped<IValidator<StoreMediaOptionSettingRequestDto>, StoreMediaOptionSettingValidation>();
        services.AddScoped<IValidator<StoreReadingSettingRequestDto>, StoreReadingSettingValidation>();
        services.AddScoped<IValidator<StoreSliderMediaRequestDto>, StoreSliderMediaValidation>();
        services.AddScoped<IValidator<StoreSliderRequestDto>, StoreSliderValidation>();
        services.AddScoped<IValidator<StoreRequestDto>, StoreValidation>();
        services.AddScoped<IValidator<StoreWritingSettingRequestDto>, StoreWritingSettingValidation>();
        services.AddScoped<IValidator<TagRequestDto>, TagValidation>();
        services.AddScoped<IValidator<TagRequestDto>, TagValidation>();
        services.AddScoped<IValidator<ZarinPalSettingRequestDto>, ZarinPalSettingValidation>();
        services.AddScoped<IValidator<MultiMediaFileRequestDto>, MultiMediaFileValidation>();
        services.AddScoped<IValidator<MainBusinessSettingRequestDto>, MainBussimnessSettingValidation>();
        services.AddScoped<IValidator<MainStoreMediaOptionSettingRequestDto>,
            MainStoreMediaOptionSettingValidation>();
        services.AddScoped<IValidator<CommentPosetiveNegativePointRequestDto>,
            CommentPosetiveNegativePointValidation>();


        services.AddScoped<IContentService, ContentService>();
        services.AddScoped<IAccountService, AccountService>();
        services.AddScoped<IProductService, ProductService>();
        services.AddScoped<ICommentService, CommentService>();
        services.AddScoped<IMultiMediaFileService, MultiMediaFileService>();
        services.AddScoped<IInstallmentInvoiceService, InstallmentInvoiceService>();
        services.AddScoped<IInvoiceService, InvoiceService>();
        services.AddScoped<IOrderNoteService, OrderNoteService>();
        services.AddScoped<IOrderTrackingService, OrderTrackingService>();
        services.AddScoped<IPostService, PostService>();
        services.AddScoped<ICategoryService, CategoryService>();
        services.AddScoped<IProductInstallmentService, ProductInstallmentService>();
        services.AddScoped<IDiscountPriceService, DiscountPriceService>();
        services.AddScoped<IPriceService, PriceService>();
        services.AddScoped<IDownloadableFileService, DownloadableFileService>();
        services.AddScoped<IVariableProductService, VariableProductService>();
        services.AddScoped<IProductSpecialOfferService, ProductSpecialOfferService>();
        services.AddScoped<IPspSadadLogService, PspSadadLogService>();
        services.AddScoped<IMenuService, MenuService>();
        services.AddScoped<IPayPalSettingService, PayPalSettingService>();
        services.AddScoped<IZarinPalSettingService, ZarinPalSettingService>();
        services.AddScoped<ICouponService, CouponService>();
        services.AddScoped<IStoreGeneralSellingSettingsService, StoreGeneralSellingSettingsService>();
        services.AddScoped<IStoreInventorySettingService, StoreInventorySettingService>();
        services.AddScoped<IShippingClassService, ShippingClassService>();
        services.AddScoped<IShippingMethodService, ShippingMethodService>();
        services.AddScoped<IShippingOptionService, ShippingOptionService>();
        services.AddScoped<IShippnigZoneService, ShippnigZoneService>();
        services.AddScoped<IStoreGroupService, StoreGroupService>();
        services.AddScoped<IStoreAddressService, StoreAddressService>();
        services.AddScoped<IStoreDiscussionSettingService, StoreDiscussionSettingService>();
        services.AddScoped<IStoreGeneralSettingService, StoreGeneralSettingService>();
        services.AddScoped<IStoreLowThresoldNotificationManagmentSettingService, StoreLowThresoldNotificationManagmentSettingService>();
        services.AddScoped<IStoreMediaOptionSettingService, StoreMediaOptionSettingService>();
        services.AddScoped<IStoreReadingSettingService, StoreReadingSettingService>();
        services.AddScoped<IStoreWritingSettingService, StoreWritingSettingService>();
        services.AddScoped<IFAQService, FAQService>();
        services.AddScoped<IStoreService, StoreService>();
        services.AddScoped<ITagService, TagService>();
        services.AddScoped<IBrandService, BrandService>();
        services.AddScoped<ICommentPosetiveNegativePointService, CommentPosetiveNegativePointService>();
        services.AddScoped<IMainBussimnessSettingService, MainBusinessSettingService>();
        services.AddScoped<IMainStoreMediaOptionSettingService, MainStoreMediaOptionSettingService>();
        services.AddScoped<StoreTypeService>();
        services.AddScoped<IMultiMediaFileService, MultiMediaFileService>();
    }
}